# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  BUILD_DIR: build
  INSTALL_DIR: install

tasks:
  default:
    desc: Run the project
    cmds:
      - task: run

  clean:
    desc: Clean build artifacts
    cmd: rm -rf {{.BUILD_DIR}} {{.INSTALL_DIR}}

  configure:
    desc: Configure the project
    requires:
      vars: [PRESET]
    cmd: cmake --preset {{.PRESET}}

  build:
    desc: Build the project
    requires:
      vars: [PRESET]
    cmd: cmake --build --preset {{.PRESET}} {{if .TARGET}}--target {{.TARGET}}{{end}}

  install:
    desc: Install the project
    cmd: cmake --install {{.BUILD_DIR}}

  run:
    desc: Configure/Build/Run the project example
    vars:
      PRESET: redis
    cmds:
      - task: configure
        vars:
          PRESET: "{{.PRESET}}"
        if: '[ {{.ENABLE_CONFIGURE}} = "true" ]'
      - task: build
        vars:
          PRESET: "{{.PRESET}}"
          TARGET: "{{.TARGET}}"
      - task: install
    silent: true
